version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.2.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm test -- --verbose --coverage
      - run: npm run build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
